### ISSUE TITLE
bug after install

### ISSUE THREAD

**Issue by gianpesto** [DieSchittigs/yeoman-contao#5]
The last build is throwing errors right after install:
ran with node 10.16.0

`npm run watch`

1.
```
@extend .small;
     ^
".image_container .caption" failed to @extend ".small".
The selector ".small" was not found.
```

2. the options for the css-loader are buggy:
`ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.`

**Comment by tophcodes** [comment]
These errors have been fixed in some of the intermediate commits since `0.3.2`, but no release was ever published from those.

I just published a new version `0.3.4`, which compiles fine.
